//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEN_BUOI8
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class Students
    {
        public int StudentId { get; set; }
        public string FullName { get; set; }
        public int Age { get; set; }
        public string Major { get; set; }
    }

    public class SchoolContext : DbContext
    {
        public SchoolContext() : base("name=SchoolContext")
        {
        }

        public DbSet<Students> Students { get; set; }
    }
}